paths:
  .github/workflows/{update-compose-multiplatform,specs-*}.yml:
    ignore:
      - 'property "workflow_(repository|sha)" is not defined in object type'
  .github/workflows/update-compose-multiplatform.yml:
    ignore:
      - 'input "client-id" is not defined in action "actions/create-github-app-token@v3"'
      - 'missing input "app-id" which is required by action "actions/create-github-app-token@v3"'
  .github/workflows/release.yml:
    ignore:
      - 'description is required in metadata of "Move the major tag" action'
