version: 2
updates:
  - package-ecosystem: github-actions
    directories:
      - /
      - /.github/actions/*
    schedule:
      interval: daily
    open-pull-requests-limit: 1
    commit-message:
      prefix: ci
      include: scope
    groups:
      minor-and-patch:
        update-types:
          - minor
          - patch
  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: daily
    open-pull-requests-limit: 1
    commit-message:
      prefix: build
      include: scope
    groups:
      minor-and-patch:
        update-types:
          - minor
          - patch
