#!/bin/sh
set -eu
jq -cn '$ARGS.positional' --args -- "$@" >> "$RUNNER_TEMP/gh-calls.jsonl"
case "${1:-} ${2:-}" in
  "api /user")
    echo '{"login":"octocat"}'
    ;;
  "api /users/"*)
    jq -cn --arg login "${2#/users/}" '{login: $login, id: 1}'
    ;;
  "pr list")
    echo '[]'
    ;;
  "pr create")
    repository=""
    previous=""
    for argument in "$@"; do
      if [ "$previous" = "--repo" ]; then
        repository="$argument"
      fi
      previous="$argument"
    done
    echo "https://github.com/$repository/pull/1"
    ;;
  "pr merge")
    ;;
  *)
    echo "The fake gh does not support gh $*." >&2
    exit 1
    ;;
esac
