name: Update the version catalog and the yarn.lock files
inputs:
  update-js-yarn-lock:
    required: true
  update-wasm-yarn-lock:
    required: true
  jdk-distribution-to-update-yarn-lock:
    required: false
  jdk-version-to-update-yarn-lock:
    required: false
  maven-repository:
    required: true
  changelog:
    required: true
  update-directory:
    required: true
runs:
  using: composite
  steps:
    - name: Set up the JDK to update the yarn.lock files
      if: inputs.update-js-yarn-lock == 'true' || inputs.update-wasm-yarn-lock == 'true'
      uses: actions/setup-java@v6
      with:
        distribution: ${{ inputs.jdk-distribution-to-update-yarn-lock }}
        java-version: ${{ inputs.jdk-version-to-update-yarn-lock }}
      env:
        GITHUB_TOKEN: ${{ github.token }}
    - name: Set up Gradle
      if: inputs.update-js-yarn-lock == 'true' || inputs.update-wasm-yarn-lock == 'true'
      uses: gradle/actions/setup-gradle@v6
    - name: Update the version catalog and the yarn.lock files
      shell: bash
      env:
        UPDATE_JS_YARN_LOCK: ${{ inputs.update-js-yarn-lock }}
        UPDATE_WASM_YARN_LOCK: ${{ inputs.update-wasm-yarn-lock }}
        MAVEN_REPOSITORY: ${{ inputs.maven-repository }}
        CHANGELOG: ${{ inputs.changelog }}
        UPDATE_DIRECTORY: ${{ inputs.update-directory }}
      run: |
        kotlin "$GITHUB_ACTION_PATH/../../../scripts/update-compose-multiplatform.main.kts" prepare \
          --update-js-yarn-lock "$UPDATE_JS_YARN_LOCK" \
          --update-wasm-yarn-lock "$UPDATE_WASM_YARN_LOCK" \
          --maven-repository "$MAVEN_REPOSITORY" \
          --changelog "$CHANGELOG" \
          --update-directory "$UPDATE_DIRECTORY"
