name: Specification
on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:
permissions: {}
jobs:
  update-version-catalog:
    name: should update Compose Multiplatform and its related libraries in the right combination
    permissions:
      contents: read
    uses: ./.github/workflows/specification-update-version-catalog.yml
    with:
      app-client-id: fake-client-id
    secrets:
      app-private-key: fake-private-key
  update-yarn-lock:
    name: update-yarn-lock
    permissions:
      contents: read
    uses: ./.github/workflows/specification-update-yarn-lock.yml
    with:
      app-client-id: fake-client-id
    secrets:
      app-private-key: fake-private-key
  enable-auto-merge:
    name: GitHub App
    permissions:
      contents: read
    uses: ./.github/workflows/specification-enable-auto-merge.yml
    with:
      app-client-id: fake-client-id
    secrets:
      app-private-key: fake-private-key
